feat: create the HeaderMainFunkhaus (#867)
* adds components list

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md

* adds notes

* Update COMPONENTS.md

* claimed component

* Update COMPONENTS.md

* claim a component

* claim a component

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md

* take a component

* take a component

* take a component

* Update COMPONENTS.md

* Update COMPONENTS.md

* Adjust the component name - already exists

* take a component

* take a component

* Update COMPONENTS.md

- marks footer as already existing

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md - marking BentoPod

* add component

* add component

* Update COMPONENTS.md

* Update COMPONENTS.md

* take a component

* take a component

* fix component description

* Update COMPONENTS.md

Component exists

* Update COMPONENTS.md

* change component's name

* Update COMPONENTS.md

Clean up the list somewhat - added a new component for the bento-box-result, as bento-bod is allready.a different component.
- removed a footer component as it doesn't really exist.
- added some checkboxes to taken/completed compoents

* take a component

* take a component

* take a component

* remove AssetFeaturedImage definition

* take a component

* take a components

* take a components

* take a component

* take a component

* add a new line

* add detailed component description

* add detailed component description

* take a component

* update component description

* Adds a button component

* Update COMPONENTS.md

* Update COMPONENTS.md

* Update COMPONENTS.md

* Clean up components.md

* Taking the block-collection component

* Taking the grid-collections component as well.

* Update COMPONENTS.md

* Clean up component list

* add spacing

* add spacing

* update component name

* Update Button definition

* Update COMPONENTS.md

* Update COMPONENTS.md

* Remove duplicates

* remove duplicates

* remove duplicates

* Remove already existing components

* take a component

* update package

* add a component

* Take a component

* adjust prop for block anchor nav

* take a component

* Update COMPONENTS.md

* Taking the DropdownSingleSelect

* Take the ButtonDropdownSearch component

* adding the correct packageMenager version for netlify to see.

pnpm
Netlify supports pnpm for Node.js 16.9.0 and later.

If your site’s base directory includes a pnpm-lock.yaml file, we will run pnpm install to install the dependencies listed in your package.json.

To specify a pnpm version, you can edit your package.json file:

"packageManager": "pnpm@6.3.2"

This tells Corepack to use and download your preferred pnpm version instead of the default version that Netlify sets.

* Update COMPONENTS.md

* Marking a component as taken

* Remove packageManager field from package.json

* Update component statuses and remove completed items

Updated the status of various components to reflect their existence and removed existing components from the list.

* Update COMPONENTS.md

* Taking the FiltersDropdown

* Update COMPONENTS.md

* Add note regarding existing header component tweaks

Added a note about existing similar functionality that requires tweaks.

* Update RefineSearchPanel ownership in COMPONENTS.md

* Update DetailMedia component owner to Svebor

* Update component list

* Clarify CTAHexButton entry in COMPONENTS.md

* Update COMPONENTS.md to remove and modify components

Removed BlockMediaViewer and updated BlockRichText entry. Adjusted completion status for DetailMedia.

* Update component status and ownership in COMPONENTS.md

* Update component ownership in COMPONENTS.md

* feat: crrates the header main funkhaus component

* Adds the brand bar to the header

* Adds a slot for the search bar

* adjusting the slot for searchbar

* Adds the borders to the header and to the slotted item

* remove the searchbar slot from the header

* Update _header-main-funkahaus.scss

* add the secondary nav header to the header.

- refactor how the menu works, not using a slot for the menu items any longer, doesn't make sense.

* Update package.json

* fix: run lint fix

* Create HeaderMainFunkhaus.spec.js

* chore: adjust story

* fix: CI Percy error

Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration

* Adds review notes, adjusts the existing header to be like the DLC theme.

* run lint fix

* feat: Styles the expanded-menu part of the header to look like the panel menu

* chore: run lint fix

* removes risidual code line

* chore: run lint fix after adding updates

* fix: simplify the account button logic, remove left over emit and function for emits.

- adjusts story to fit new narrative
- adjust parent components

* fix:run lint

---------

Co-authored-by: dchiamp <derek.chiampas@gmail.com>
Co-authored-by: Austin Blanchard <austinpdx@gmail.com>
Co-authored-by: Luka Vuk <61590027+lux-v@users.noreply.github.com>
Co-authored-by: Jess <jessica.divers@gmail.com>