feat: APPS-2561 convert flexible-media-with-text component to vue3 (#469)
* feat: add Flexible_MediaWithText files

* update: add vue3 syntax update

* chore: linting

* add flexible types

* chore: linting

* chore: linting

* chore: lint

* delete CardWthImage file that was accidentally added

* fix linting error

* add upload to typescript

* add usrc to typescript

* update the logoc for the parsedButtonUrl

* fix logic

* comment out styles and fix storybookgit status

* fix mobile styling

* remove the native modifier per vue3 specification

* fix error about the boolean appearing as the string "true"

`src/lib-components/BlockMediaWithText.vue(113,11): error TS2322: Type 'string' is not assignable to type 'boolean | undefined'.
`

https://stackoverflow.com/questions/69014714/angular-ts2322-type-string-is-not-assignable-to-type-boolean

* fix coverOnly

* fix coverOnly

* remove extraneous h3 for test

* un comment smart-link

* update comment

* comment out smart-link again

* clightbox will NOT open if OTHER

* update Flexible_MediaWithTxt.js mock data for storybook

* linting

* comment out smart link import

* comment out smart link import